apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-source
      role: node-source
  template:
    metadata:
      labels:
        app: node-source
        role: node-source
    spec:
      containers:
      - name: node-source
        image: bonnce/node-source:5275e241443123f47ed4cea078704572a480919f
        ports:
        - containerPort: 8889
          protocol: TCP
#comentario
