apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-source
      role: node-source
  template:
    metadata:
      labels:
        app: node-source
        role: node-source
    spec:
      containers:
      - name: node-source
        image: bonnce/node-source:7dbae70997906fb5ce1fdf4e38baa69852a9efc0
        ports:
        - containerPort: 8889
          protocol: TCP
